### ISSUE TITLE
DTDs when not validating

### ISSUE THREAD

**Issue by gmoore016** [sul-cidr/patent_data_extractor#5]
@simonwiles 

Hi Simon,

Now that we've set the parser to default to not validating, does it still need the DTD? At the moment I get an error if I don't specify a DTD even if I don't ask to validate. This no longer seems necessary, is that right?

**Comment by simonwiles** [comment]
No, you'll still need the DTDs to resolve entities and some other namespace values.  It might be possible to hack around this (see https://github.com/sul-cidr/patent_data_extractor/blob/master/patent_xml_to_csv.py#L27-L35 where I've hacked around the remaining entities that can't be resolved even with the best set of DTDs we have), but even insofar as it's possible I don't think it would be desirable.

**Comment by gmoore016** [comment]
Sounds good, thanks for the clarification!
